"""Model compatibility shim for Argon.

Re-exports all Argon ORM models from app.argon.models under their original
names so that internal modules (worker.py, services, etc.) can import from
this single namespace without knowing the physical file layout.
"""

from app.argon.models import (  # noqa: F401
    get_embedding_model_for_dim,
    WORKSPACE_ROLE_HIERARCHY,
    AppConfig,
    AuditLog,
    Base,
    Department,
    EmbeddingJob,
    Employee,
    KnowledgeType,
    MCPQueryLog,
    Note,
    Notification,
    Project,
    ProjectMember,
    ProjectSource,
    Role,
    ScopeType,
    Skill,
    SkillContribution,
    SkillDepartment,
    SkillVersion,
    Source,
    SourceChunkExtract,
    SourceCompilationPlan,
    SourceDepartment,
    SourceImage,
    StatsDailyRollup,
    WikiDraftRound,
    WikiLink,
    WikiPage,
    WikiPageDraft,
    WikiPageEmbedding768,
    WikiPageEmbedding1024,
    WikiPageEmbedding1536,
    WikiPageEmbedding3072,
    WikiPageRevision,
    WorkspaceRole,
    SkillContributionStatus,
)

__all__ = [
    "get_embedding_model_for_dim",
    "WORKSPACE_ROLE_HIERARCHY",
    "AppConfig",
    "AuditLog",
    "Base",
    "Department",
    "EmbeddingJob",
    "Employee",
    "KnowledgeType",
    "MCPQueryLog",
    "Note",
    "Notification",
    "Project",
    "ProjectMember",
    "ProjectSource",
    "Role",
    "ScopeType",
    "Skill",
    "SkillContribution",
    "SkillDepartment",
    "SkillVersion",
    "Source",
    "SourceChunkExtract",
    "SourceCompilationPlan",
    "SourceDepartment",
    "SourceImage",
    "StatsDailyRollup",
    "WikiDraftRound",
    "WikiLink",
    "WikiPage",
    "WikiPageDraft",
    "WikiPageEmbedding768",
    "WikiPageEmbedding1024",
    "WikiPageEmbedding1536",
    "WikiPageEmbedding3072",
    "WikiPageRevision",
    "WorkspaceRole",
    "SkillContributionStatus",
]
